config/routes.rb
Rails.application.routes.draw do

  root 'blogs#index'

  resources :blogs do
    resources :comments
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  validates :name, presence: true
  validates :author, presence: true
  validates :content, presence: true
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: :true
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    blog = Blog.new params[:blog].permit(:name, :content, :description, :author)
    if blog.save
      redirect_to '/'
    else
      render 'new'
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @blog = Blog.find(params[:blog_id])
  end

  def create
    blog = Blog.find(params[:blog_id])
    blog.comments << Comment.create(params[:comment].permit(:content))
    redirect_to blog_path(params[:blog_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blogs/index.html.erb
<%= link_to('Add a blog', new_blog_path, class: 'add-blog-link') %>


  <% @blogs.each do |blog| %>
    <div class="blog-details">
      <h3><%= blog.name %></h3>  
      <h5><%= blog.author %></h5>
      <p><%= blog.description %></p>
      <%= link_to('Read me...',blog_path(blog.id)) %>
    </div> 
  <% end %>  

app/views/blogs/new.html.erb
<%= form_for @blog do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1>
<h3><%= @blog.author %></h3>

<article><%= @blog.content %></article>

<%= link_to('Comment', new_blog_comment_path(@blog.id)) %>

<% @blog.comments.each do |comment| %>
  <%= comment.content %>
<% end %>

app/views/comments/new.html.erb
<%= form_for [@blog, @comment] do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit 'Submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TddBlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>